// ESLint flat configuration: @eslint/js recommended rules for every linted file,
// with language options per file kind. No formatting rules (no formatter is used).
import js from "@eslint/js";
import globals from "globals";

export default [
  {
    ignores: [
      "node_modules/**",
      "webaudio-tinysynth.min.js",  // generated by npm run build
      "*.map",
      "bower_components/**",        // vendored demo controls
      "docs/improvements/evidence/**", // frozen T0 probe evidence
    ],
  },
  js.configs.recommended,
  {
    // The library: a classic browser script wrapped in (function(window){...})(this)
    // that exports through CommonJS, AMD or a global. Only the globals it uses are
    // declared, so a misspelled or accidental global still fails no-undef.
    files: ["webaudio-tinysynth.js"],
    languageOptions: {
      sourceType: "script",
      globals: {
        AudioContext: "readonly",
        XMLHttpRequest: "readonly",
        clearInterval: "readonly",
        console: "readonly",
        performance: "readonly",
        setInterval: "readonly",
        define: "readonly",
        exports: "readonly",
        module: "readonly",
      },
    },
    rules: {
      // The library keeps ES2015 syntax, which needs a binding in every catch
      // clause; its empty catch blocks say in a comment why the error is ignored.
      "no-unused-vars": ["error", { caughtErrors: "none" }],
    },
  },
  {
    files: ["tests/**/*.js", "tests/**/*.cjs", "scripts/**/*.js", "**/*.cjs"],
    languageOptions: {
      sourceType: "commonjs",
      globals: globals.node,
    },
  },
  {
    files: ["**/*.mjs"],
    languageOptions: {
      sourceType: "module",
      globals: globals.node,
    },
  },
];
