/*
 * Initialization cost (#18, ledger L-16) in the main V8 realm, where the library's own
 * Math.sin and typed-array code runs at full speed (the Vitest unit tests run it inside vm
 * contexts, about 15 times slower): each build, loaded with require(), on the harness's mock
 * context at 44.1 kHz. With useReverb 0 there is no convBuf; n1 is not generated until it is
 * read, and then holds the seeded expectations (tests/browser/specs/seed-expected.js, from an
 * independent reference) and is generated once. Generation is counted with Math.sin, which
 * only n1 calls (2 * 64 * 22050 times). The unit tests in tests/unit/init-cost.test.mjs cover
 * the rest.
 */
"use strict";
const test = require("node:test");
const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const H = require("../harness");
const { SEED_EXPECTED: E } = require("../browser/specs/seed-expected.js");

const Ctx = H.createEnvironment([]).sandbox.AudioContext;
const N1_SINS = 2 * 64 * 22050;
const sha = (buf) => {
  const h = crypto.createHash("sha256");
  for (let c = 0; c < buf.numberOfChannels; ++c) {
    const d = buf.getChannelData(c);
    h.update(Buffer.from(d.buffer, d.byteOffset, d.byteLength));
  }
  return h.digest("hex");
};

const realSin = Math.sin;
let sins = 0;
Math.sin = (x) => { ++sins; return realSin(x); };
test.after(() => { Math.sin = realSin; });

for (const build of H.forkVariants()) {
  test.describe(build.name + " under Node", () => {
    const Synth = require(build.file);
    const make = (opts) => new Synth(Object.assign({ context: Object.assign(new Ctx(), { sampleRate: 44100 }) }, opts));
    const h = E.hashes[44100][E.defaultSeed];

    test("useReverb: 0 builds no convBuf, and n1 is generated by the first read, once, with the seeded data", () => {
      sins = 0;
      const synth = make({ useReverb: 0 });
      assert.equal(synth.convBuf, null);
      assert.equal(sins, 0, "construction does not generate n1");
      synth.noteOn(0, 60, 100, 0);
      synth.noteOn(9, 38, 100, 0);
      assert.equal(sins, 0, "a melodic note and an n0 drum do not read n1");
      synth.noteOn(9, 42, 100, 0); // quality 1's closed hi-hat plays n1
      assert.equal(sins, N1_SINS);
      assert.equal(sha(synth.noiseBuf.n0), h.n0);
      assert.equal(sha(synth.noiseBuf.n1), h.n1);
      synth.noteOn(9, 49, 100, 0);
      assert.equal(sins, N1_SINS, "later n1 notes and reads do not generate again");
      synth.dispose();
    });

    test("with reverb on the impulse is the seeded one; disposing before any n1 read never generates it", () => {
      sins = 0;
      const synth = make({});
      assert.equal(sha(synth.convBuf), h.convBuf);
      synth.dispose();
      assert.equal(sins, 0);
      assert.equal(synth.noiseBuf, null);
    });
  });
}
